import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./components/navbar"
import Navbar from "./components/navbar";
import Footer from './components/fotter'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { dark } from "@clerk/themes";

import './globals.css'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prompt Improver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <ClerkProvider
      appearance={{
        baseTheme: dark, // 🔥 enables dark mode for Clerk modals
      }}
    >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
          
          </header>
          <Navbar/>
          {children}
          
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  );
}
